[package]
name = "grossbaby"
version = "0.1.0"
edition = "2021"
authors = ["shua <shua@isthisa.email>", "ddydsz"]

# from https://bevy-cheatbook.github.io/pitfalls/performance.html
[profile.dev.package."*"]
opt-level = 3
[profile.dev]
opt-level = 1

[dependencies]
# bevy = "0.13.1" # for release
bevy = { version = "0.13.1", features = ["dynamic_linking"] } # for dev
# bevy_rapier2d = "0.18.0"
bevy_editor_pls = "0.8.1"

[[bin]]
name = "jd"
path = "jd/main.rs"

[[bin]]
name = "ad"
path = "ad/main.rs"
